# Generated by Django 3.2.6 on 2021-08-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('college', models.CharField(max_length=120, verbose_name='College Name')),
                ('phone', models.CharField(max_length=120, verbose_name='Phone')),
                ('semester', models.CharField(max_length=120, verbose_name='Semster')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
