# Generated by Django 3.2.6 on 2021-08-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210826_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='images',
        ),
    ]
