# Generated by Django 3.2.6 on 2021-08-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20210827_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='updated',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event Date'),
        ),
    ]
