# Generated by Django 3.2.6 on 2021-08-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_alter_event_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
