# Generated by Django 3.2.6 on 2021-08-27 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_auto_20210827_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 15, 58, 49, 428940, tzinfo=utc), verbose_name='Event Date'),
            preserve_default=False,
        ),
    ]
