# Generated by Django 3.2.6 on 2021-08-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_auto_20210827_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
    ]
