# Generated by Django 3.2.6 on 2021-08-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_alter_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(default='', max_length=120, verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='student',
            name='event',
            field=models.CharField(default='', max_length=120, verbose_name='Event Name'),
        ),
    ]
