# Generated by Django 3.2.6 on 2021-08-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_auto_20210827_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(verbose_name='Semester'),
        ),
    ]
